### ISSUE TITLE
Сохранение словаря

### ISSUE THREAD

**Issue by klessh** [nmud/nmud#100]
Было бы удобно сохранять словарь не в "словаре", а прямо в "рабочей зоне" редактора. Может быть, чтобы карта и словарь сохранялись по одному клику.

**Comment by iillyyaa2033** [comment]
@klessh поздравляю с сотым исью!

**Comment by iillyyaa2033** [comment]
Closed by nmud/nmud#d489b3a7c481cf39faef3942de52e3326f1715da

**Comment by klessh** [comment]
Благодарю!
