### ISSUE TITLE
Редактор: переименование

### ISSUE THREAD

**Issue by klessh** [nmud/nmud#104]
При смене имени редактор не отображает изменение. Оно работает криво.

**Comment by klessh** [comment]
Проблема в том, что приходится пересоздавать объекты, удалять старые, лазить за ними в низ списка - всё это потери во времени.

**Comment by klessh** [comment]
Вот эту штуку бы сделал.

**Comment by iillyyaa2033** [comment]
_iillyyaa2033 присматривается_

**Comment by iillyyaa2033** [comment]
Тип вот. Кинул - проверяй.

**Comment by klessh** [comment]
А оно не хочет: список объектов полностью закрывается(жутко неудобно), а переименование не отображается.

**Comment by iillyyaa2033** [comment]
Починил. Кинул на почту. Пока закрываю. Будут вопросы - переоткрой.
