### ISSUE TITLE
Редактор: подсказки параметров

### ISSUE THREAD

**Issue by klessh** [nmud/nmud#106]
Не помню - было или не было, но нужны подсказки параметров "action" и "location".

**Comment by iillyyaa2033** [comment]
@klessh подсказки по алгоритму 'запоминаем все введенное, потом подсказываем'?

**Comment by klessh** [comment]
@iillyyaa2033 Вообще, имел в виду подсказки при вводе самих параметров(аналогично "do"->"door"). Но всё введенное тоже неплохо было бы запоминать и подсказывать. Эдакий "локальный словарик". Главное чтоб при закрытии проги не забывал(кстати так с цветом происходит).
