### ISSUE TITLE
Редактор: action и location - сразу

### ISSUE THREAD

**Issue by klessh** [nmud/nmud#108]
Нужно, чтобы параметры action ­и location создавались автомат­ически, при создании ­объекта. Ведь не нужн­ы они только в комнатах и­ стенах.

**Comment by klessh** [comment]
А можно ещё сделать так, чтобы значение по умолчанию легко стиралось при нажатии? Или вообще оставлять поле пустым. А то подтирать приходится... неудобно...

**Comment by iillyyaa2033** [comment]
Можно. Но завтра утром.
