### ISSUE TITLE
Комната прислуги

### ISSUE THREAD

**Issue by klessh** [nmud/nmud#21]
Дверь в коридор, южная стена комнаты прислуги, северная стена комнаты прислуги, западная  стена комнаты прислуги, восточная стена комнаты прислуги, кровать, кровать, сундук, сундучок.

Лепленная вручную свечка, укрепленная на стене, слабо освещает комнатенку. Вдоль противоположных стен, в уголках комнаты расставлены две кровати. Правая заправлена не полностью. В торце другой, на полу стоит небольшой сундучок с резной крышкой. По другой стене, на которой держится свеча, находится сундук побольше. У его края на петлях висит грубая деревянная дверь, ведущая в коридор

**Comment by klessh** [comment]
Поправь, скажи что не так. Остальные напишу уже с правкой.

**Comment by iillyyaa2033** [comment]
Свечка откуда взялась? Где эта свечка находится?

Различие между кроватями? Сундуками? Стенами?

**Comment by klessh** [comment]
А так?

**Comment by iillyyaa2033** [comment]
Гораздо лучше. Сяб

**Comment by iillyyaa2033** [comment]
@klessh, контент обновляй - комнату проверяй

**Comment by klessh** [comment]
@iillyyaa2033 Проверять на предмет чего? Чего делать с этими исью? Они меня смущают.

**Comment by iillyyaa2033** [comment]
Проверять на предмет кошерности описаний - об этом же исью.

**Comment by iillyyaa2033** [comment]
@klessh, еще раз. Что мне от тебя нужно:
1. Обновляешь контент
2. Запускаешь ктулху
3. Заходишь в игру
4. Идешь в кухню купеческого дома
5. Пишешь `осмотреться`
6. Читаешь описание
7. Повторяешь пп 4-6 для коридора и комнаты прислуги
8. Закрываешь ктулху
9. Идешь на гитхаб, в это и соседние исью
10. Пишешь, устраивают ли тебя описания.

**Comment by klessh** [comment]
Вы находитесь в Комната прислуги.  на западной стене висит на грубых петлях красивая зеленая Дверь в коридор. в северо-восточном углу стоит Левая кровать. в юго-восточном углу стоит Правая кровать. рядом с дверью в коридор стоит Сундук. около левой кровати стоит Сундучок. 

Согласование: находимся _в комнате прислуги_, а не _в комната прислуги_.

Предложения с большой, нарицательные предметы с маленькой буквы(сундук, дверь).

Не "описан" аватар Надпочечник, запросивший описание.

**Comment by iillyyaa2033** [comment]
@klessh, теперь с описаниями все в порядке?

`Вы находитесь в комнате прислуги.  На западной стене висит на грубых петлях красивая зеленая дверь в коридор. В северо-восточном углу стоит левая кровать. В юго-восточном углу стоит правая кровать. Рядом с дверью в коридор стоит сундук. Около левой кровати стоит сундучок.`

Тогда закрывай эти три исью.
