### ISSUE TITLE
Кухня

### ISSUE THREAD

**Issue by klessh** [nmud/nmud#27]
Южная стена кухни, северная стена кухни, западная стена кухни, восточная стена кухни, дверь в коридор, бочка, печь, стол, бочка с рукомойником, дверь в прихожую. 

Вдоль восточной стены стоит крупная белая печь. Чуть правее, около стены находится пузатая бочка с чистой водой. Узкая дверь, ведущая в коридор, примостилась рядом с бочкой. У противоположной стены растянулся длинный кухонный стол, занятый утварью и продуктами: кастрюли и ковороды,  крупные ложки и кучки овощей `(все эти предметы будут позже, в качестве содержимого контейнера "стол")`. В его торце стоит ещё одна бочка, поменьше, она содержит использованную воду. Прямо над ней висит старый деревянный рукомойник. Вблизи, на соседней стене,  добротная дверь закрывает проход в прихожую.

**Comment by iillyyaa2033** [comment]
...противоположной стены **растянулся** длинный кухонный... 
@klessh, растянулся написано зря.

**Comment by iillyyaa2033** [comment]
@klessh, кухня кагбе давно уже заописана. Жду твоего комментария джва месяца.

**Comment by klessh** [comment]
Всё о том же 'растянулся'? Так это художественность...

**Comment by iillyyaa2033** [comment]
Не, я о том, что если зайдешь в кухню и осмотришься - увидишь описание.

**Comment by klessh** [comment]
Вы находитесь в Кухня.  рядом с бочкой примостилась узкая Дверь в коридор. Существует Существо. около восточной стены, между печью и дверью в коридор находится пузатая Бочка. вдоль восточной стены стоит крупная белая Печь. вдоль западной стены растянулся узкий Стол. Существует Бочка с рукомойником. на стене закрывает проход добротная Дверь в прихожую. в комнате стоит Птицекрыл. в комнате стоит Румарука. 

Согласование: находимся в _кухне_, а не в _кухня_. 

Предложения с большой, нарицательные предметы с маленькой буквы(печь, бочка).

Не "описан" аватар Надпочечник, запросивший описание.

**Comment by iillyyaa2033** [comment]
@klessh, проверяй эти три исью.

А свой аватар и не должен быть описан .
