### ISSUE TITLE
Коридор

### ISSUE THREAD

**Issue by klessh** [nmud/nmud#28]
Северная стена коридора, западная стена коридора, южная стена коридора, восточная стена коридора, дверь на кухню, дверь в комнату прислуги, лестница в подвал.

На противоположных стенах небольшой, плохо освещенной комнатки располагаются двери в кухню и комнату прислуги. У северной стены, в закутке находится лестница в подвал. На противоположной стене на крупных петлях висит дверь, ведущая на задний двор ~`(добавлю дверь, когда Ктулха будет сохранять)`~.

**Comment by iillyyaa2033** [comment]
У **другой** стены... Заменил на северную.

**Comment by iillyyaa2033** [comment]
@klessh контент обновляй - коридор проверяй

**Comment by klessh** [comment]
Вы находитесь в Коридор.  в западной стене прорублена Дверь в кухню. в восточной стене прорублена Дверь в комнату прислуги. у северной стены находится Лестница в подвал. на южной стене висит на крупных петлях Дверь во двор. 

Согласование: находимся в _коридоре_, а не в _коридор_.

Предложения с большой, нарицательные предметы с маленькой буквы(лестница, дверь).

Не "описан" аватар Надпочечник, запросивший описание.
