### ISSUE TITLE
Последнее по сетке

### ISSUE THREAD

**Issue by klessh** [nmud/nmud#48]
Нужно чтобы сетка с шагом в 0.1(пусть даже без цифр) появлялась раньше. 

Сейчас эта сетка мало применима, ибо с тем масштабом, которому она соотвествует, работать неудобно.

**Comment by klessh** [comment]
Сейчас эта сетка мало применима, ибо с тем масштабом, которому она соотвествует, работать неудобно.

**Comment by iillyyaa2033** [comment]
Склеил сообщения.

Клещ, а у тебя планш нормально тянет 0.1 шаг? Не начинает тормозить?

**Comment by klessh** [comment]
По сути, значения на сетке с шагом в 0.1 не нужны.

**Comment by iillyyaa2033** [comment]
Не в значениях дело. Но это не важно. Ибо переписывать отрисовку карты буду я.

**Comment by klessh** [comment]
Понимаю, что дело не в них. Говорю, что они не нужны.
