### ISSUE TITLE
Масштабирование

### ISSUE THREAD

**Issue by klessh** [nmud/nmud#49]
При изменении масштаба 'от сетки в 0.1' сильно уводит в сторону.

**Comment by iillyyaa2033** [comment]
Ошибки округления. Не уверен, что смогу решить эту проблему, но попробую.

**Comment by iillyyaa2033** [comment]
@klessh, не написал нормально раньше, напишу сейчас.

То, что карту уводит в сторону (точнее, к 0:0) - это баг из-за неправильных формул, и я его поравлю.

То, что пишется 0.99 вместо 1.0 - это баг из-за ошибок округления. Я его тоже поправлю, но позже.

**Comment by klessh** [comment]
Ошибки округление и увод в сторону не так мешают. Но 'сползающие' в сторону объекты не дают работать с картой.

**Comment by iillyyaa2033** [comment]
Поправлю.

Когда буду переписывать вьюху карты - а переписать ее надо - многие проблемы отрисовки будут решены.

**Comment by klessh** [comment]
Сегодня полез создавать дворы - тот ещё геморрой: неудобный масштаб, дабы не сползало; много страшных цифр... убивает всё вдохновение... По возможности, пожалуйста, повысь приоритет задачи.

**Comment by iillyyaa2033** [comment]
Некуда. У багов самый высокий приоритет.
