### ISSUE TITLE
Открытие предыдущего файла

### ISSUE THREAD

**Issue by klessh** [nmud/nmud#56]
Вместе с предложением открыть предыдущий файл-карту вылазит "открыть с помощью" - выбор программы. Хотя должно вылазить только в случае неоткрытия последнего файла.

**Comment by iillyyaa2033** [comment]
Возможно, это предложение выбрать файл словаря (ты же еще его не выбирал, да?).

В любом случае, это баг. Я посмотрю, что можно сделать.

**Comment by klessh** [comment]
Да, осталась.

**Comment by iillyyaa2033** [comment]
@klessh, а если стереть данные, удалить редактор, а затем поставить тот, что я прислал утром?

**Comment by iillyyaa2033** [comment]
@klessh, тебе на почту пришел редактор от 16 авг?

**Comment by klessh** [comment]
Да, всё нормально работает. Исью можно закрывать.

**Comment by iillyyaa2033** [comment]
Отлично!
