### ISSUE TITLE
Эмоциалы

### ISSUE THREAD

**Issue by klessh** [nmud/nmud#58]
Команда позволяет описать малозначительное, не на что не влияющее действие "словами сервера". Отыгрыш.
Пример: " 'команда' почесал за ухом" -> " 'игрок' почесал за ухом".

**Comment by iillyyaa2033** [comment]
Забил командой 'я' и '/' (слэш)
`я почесал за ухом` -> `Румарука почесал за ухом`
`/ удивился` -> `Румарука удивился`
