### ISSUE TITLE
Взять

### ISSUE THREAD

**Issue by klessh** [nmud/nmud#59]
Применимо к любым подъемным объектам, находящимся в мире.

Действие: перемещение предмета из мира непосредственно в руки.

"Взять луковицу со стола"

Блоки:
[_что-либо_] - предмет, с которым совершается действие
[_из(с) чего-либо_] - контейнер, в котором изначально находится предмет
[_с чего-либо_] - контейнер, на котором изначально находится предмет

**Comment by iillyyaa2033** [comment]
@klessh, 'подъемные' предметы - это сущности с тэгом `pickable`, если что.
