### ISSUE TITLE
Большие буквы

### ISSUE THREAD

**Issue by klessh** [nmud/nmud#68]
В сл­оваре все слова забит­ы с маленькой буквы, ­поэтому и названия об­ъектов отображается с­ маленькой буквы. А нужно чтоб отображались с большой.

**Comment by iillyyaa2033** [comment]
@klessh, так забей с большой, в чем проблема?
![image0005](https://user-images.githubusercontent.com/17745136/29303923-d8b0d78c-8198-11e7-8f8c-faa89de17cc6.png)
