### ISSUE TITLE
'Несмена' имени

### ISSUE THREAD

**Issue by klessh** [nmud/nmud#80]
После выбора нового имени в словаре (смене имени), нажатия 'use this' возвращаемся обратно в редактор, но ничего не меняется.

**Comment by iillyyaa2033** [comment]
@klessh, а если еще раз нажать на пункт 'Имя'?

**Comment by klessh** [comment]
Дошел, в нем баг и нашел.

Еслт ещё раз нажать, показывает старое.

**Comment by iillyyaa2033** [comment]
@klessh, никак не могу воспроизвести баг.  Можешь кинуть скрины и попунктное объяснение, что и как делал?

Скрины можно кидать прямо сюда.
![image0005](https://user-images.githubusercontent.com/17745136/29399477-1034043c-8332-11e7-961c-1d762f727971.png)

**Comment by klessh** [comment]
В скинутой 17 авг версии редактора бага нет.

**Comment by klessh** [comment]
А обратно открыть можешь? Бага всё таки осталась: имя меняется, и на карте отображается новое, а вот в поле ввода и в списке остается старое. Примечательно, что у скопированного объекта всюду отображается новое имя.

**Comment by iillyyaa2033** [comment]
Тогда моя просьба о пояснении остается в силе.

**Comment by klessh** [comment]
Но ведь я же расписал

**Comment by iillyyaa2033** [comment]
А, все. Вижу в почте.

**Comment by iillyyaa2033** [comment]
@klessh, нет. Все таки не нашел. В почте объяснения нет. В этой ветке - тоже. Посмотри мою просьбу четырьмя ответами выше (та, что со скриншотом) - мы говорим об одном и том же?

**Comment by iillyyaa2033** [comment]
А нет, вот же оно. Надо выспаться.
